CREATE TYPE "input_characteristics_type" AS ENUM (
    'number',
    'measuring',
    'text',
    'boolean',
    'media',
    'video'
    );

CREATE TYPE "service_modifiers_type" AS ENUM (
    'single',
    'multiple'
    );

CREATE TYPE "service_type" AS ENUM (
    'creation',
    'selling'
    );

CREATE TYPE "service_status" AS ENUM (
    'base_info_required',
    'media_required',
    'active',
    'disabled'
    );

CREATE TABLE "services"
(
    "id"             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name"           varchar        NOT NULL,
    "base_price"     numeric(14, 2) NOT NULL CHECK ("base_price" >= 0),
    "description"    text,
    "type"   service_type   NOT NULL,
    "status" service_status NOT NULL,
    "created_at"     timestamptz    NOT NULL DEFAULT now(),
    "updated_at"     timestamptz    NOT NULL DEFAULT now()
);

CREATE TABLE "service_categories"
(
    "id"         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name"       varchar     NOT NULL UNIQUE,
    "created_at" timestamptz NOT NULL DEFAULT now(),
    "updated_at" timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE "service_category_services"
(
    "service_id"          integer NOT NULL,
    "service_category_id" integer NOT NULL,

    PRIMARY KEY (
                 "service_id",
                 "service_category_id"
        ),

    CONSTRAINT "service_categories_creation_service_id_fk"
        FOREIGN KEY ("service_id")
            REFERENCES "services" ("id")
            ON DELETE CASCADE
            DEFERRABLE INITIALLY IMMEDIATE,

    CONSTRAINT "service_categories_service_category_id_fk"
        FOREIGN KEY ("service_category_id")
            REFERENCES "service_categories" ("id")
            ON DELETE CASCADE
            DEFERRABLE INITIALLY IMMEDIATE
);

CREATE TABLE "input_characteristics_templates"
(
    "id"          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name"        varchar     NOT NULL,
    "description" text,
    "created_at"  timestamptz NOT NULL DEFAULT now(),
    "updated_at"  timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE "input_characteristics"
(
    "id"         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name"       varchar                    NOT NULL,
    "type"       input_characteristics_type NOT NULL,
    "created_at" timestamptz                NOT NULL DEFAULT now(),
    "updated_at" timestamptz                NOT NULL DEFAULT now()
);

CREATE TABLE "input_characteristic_template_items"
(
    "template_id"             integer NOT NULL,
    "input_characteristic_id" integer NOT NULL,

    PRIMARY KEY (
                 "template_id",
                 "input_characteristic_id"
        ),

    CONSTRAINT "input_characteristic_template_items_template_id_fk"
        FOREIGN KEY ("template_id")
            REFERENCES "input_characteristics_templates" ("id")
            ON DELETE CASCADE
            DEFERRABLE INITIALLY IMMEDIATE,

    CONSTRAINT "input_characteristic_template_items_input_characteristic_id_fk"
        FOREIGN KEY ("input_characteristic_id")
            REFERENCES "input_characteristics" ("id")
            ON DELETE CASCADE
            DEFERRABLE INITIALLY IMMEDIATE
);

CREATE TABLE "service_media_files"
(
    "id"         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "service_id" integer     NOT NULL,
    "file_url"   text        NOT NULL,
    "sort_order" integer CHECK ("sort_order" >= 0),
    "created_at" timestamptz NOT NULL DEFAULT now(),
    "updated_at" timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT "service_media_files_service_id_fk"
        FOREIGN KEY ("service_id")
            REFERENCES "services" ("id")
            ON DELETE CASCADE
            DEFERRABLE INITIALLY IMMEDIATE
);

CREATE TABLE "service_input_characteristics"
(
    "input_characteristics_id" integer NOT NULL,
    "service_id"               integer NOT NULL,
    "is_required"              boolean NOT NULL DEFAULT true,
    "sort_order"               integer CHECK ("sort_order" >= 0),

    PRIMARY KEY (
                 "input_characteristics_id",
                 "service_id"
        ),

    CONSTRAINT "service_input_characteristics_input_characteristics_id_fk"
        FOREIGN KEY ("input_characteristics_id")
            REFERENCES "input_characteristics" ("id")
            DEFERRABLE INITIALLY IMMEDIATE,

    CONSTRAINT "service_input_characteristics_service_id_fk"
        FOREIGN KEY ("service_id")
            REFERENCES "services" ("id")
            ON DELETE CASCADE
            DEFERRABLE INITIALLY IMMEDIATE
);

CREATE TABLE "service_modifiers"
(
    "id"             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "service_id"     integer                NOT NULL,
    "name"           varchar                NOT NULL,
    "selection_type" service_modifiers_type NOT NULL,
    "sort_order"     integer CHECK ("sort_order" >= 0),
    "is_required"    boolean                NOT NULL DEFAULT true,

    CONSTRAINT "service_modifiers_service_id_fk"
        FOREIGN KEY ("service_id")
            REFERENCES "services" ("id")
            ON DELETE CASCADE
            DEFERRABLE INITIALLY IMMEDIATE

);

CREATE TABLE "service_modifier_values"
(
    "id"                  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name"                varchar        NOT NULL,
    "service_modifier_id" integer        NOT NULL,
    "additional_price"    numeric(14, 2) NOT NULL DEFAULT 0 CHECK ("additional_price" >= 0),
    "is_active"           boolean        NOT NULL DEFAULT true,
    "sort_order"          integer CHECK ("sort_order" >= 0),
    "created_at"          timestamptz    NOT NULL DEFAULT now(),
    "updated_at"          timestamptz    NOT NULL DEFAULT now(),

    CONSTRAINT "service_modifier_values_service_modifier_id_fk"
        FOREIGN KEY ("service_modifier_id")
            REFERENCES "service_modifiers" ("id")
            ON DELETE CASCADE
            DEFERRABLE INITIALLY IMMEDIATE
);

CREATE TABLE "service_products"
(
    "id"                    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "service_id"            integer        NOT NULL,
    "name"                  varchar        NOT NULL,
    "auto_calculated_price" numeric(14, 2) NOT NULL CHECK ("auto_calculated_price" >= 0),
    "confirmed_price"       numeric(14, 2) NOT NULL CHECK ("confirmed_price" >= 0),
    "comment"               text,
    "created_at"            timestamptz    NOT NULL DEFAULT now(),
    "updated_at"            timestamptz    NOT NULL DEFAULT now(),

    CONSTRAINT "service_products_service_id_fk"
        FOREIGN KEY ("service_id")
            REFERENCES "services" ("id")
            ON DELETE CASCADE
            DEFERRABLE INITIALLY IMMEDIATE
);

CREATE TABLE "service_product_input_characteristics_values"
(
    "id"                       integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "input_characteristics_id" integer     NOT NULL,
    "service_product_id"       integer     NOT NULL,
    "number_value"             numeric,
    "measuring_value"          numeric,
    "text_value"               text,
    "boolean_value"            boolean,
    "media_file"               text,
    "created_at"               timestamptz NOT NULL DEFAULT now(),
    "updated_at"               timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT "input_characteristics_values_input_characteristics_id_fk"
        FOREIGN KEY ("input_characteristics_id")
            REFERENCES "input_characteristics" ("id")
            DEFERRABLE INITIALLY IMMEDIATE,

    CONSTRAINT "input_characteristics_values_service_product_id_fk"
        FOREIGN KEY ("service_product_id")
            REFERENCES "service_products" ("id")
            ON DELETE CASCADE
            DEFERRABLE INITIALLY IMMEDIATE,

    CONSTRAINT "input_characteristics_values_product_characteristic_unique"
        UNIQUE ("service_product_id", "input_characteristics_id"),

    CONSTRAINT "input_characteristics_values_only_one_value_check"
        CHECK (
            num_nonnulls(
                    "number_value",
                    "measuring_value",
                    "text_value",
                    "boolean_value",
                    "media_file"
            ) = 1
            )
);

CREATE TABLE "service_products_modifier_values"
(
    "service_product_id" integer NOT NULL,
    "modifier_value_id"  integer NOT NULL,

    PRIMARY KEY (
                 "service_product_id",
                 "modifier_value_id"
        ),

    CONSTRAINT "service_products_modifier_values_product_id_fk"
        FOREIGN KEY ("service_product_id")
            REFERENCES "service_products" ("id")
            ON DELETE CASCADE
            DEFERRABLE INITIALLY IMMEDIATE,

    CONSTRAINT "service_products_modifier_values_modifier_value_id_fk"
        FOREIGN KEY ("modifier_value_id")
            REFERENCES "service_modifier_values" ("id")
            ON DELETE CASCADE
            DEFERRABLE INITIALLY IMMEDIATE
);
